version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)-s %(levelname)s [%(name)s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    filename: logs/discord.log
    encoding: 'utf-8'
loggers:
  Test:
    level: DEBUG
    handlers: [ console ]
    propagate: no
root:
  level: DEBUG
  handlers: [console,file]